spring:
  datasource:
    dynamic:
      hikari:
        min-idle: 5
        max-pool-size: 20
        idle-timeout: 60000
        max-lifetime: 60000
        is-auto-commit: true
        validation-timeout: 3000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        connection-init-sql: set names latin1
      primary: master
      datasource:
        master:
          url: jdbc:mysql://192.168.25.99:3306/beibei?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=GBK&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: '@jiushi123@'
          driver-class-name: com.mysql.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        adball:
          url: jdbc:mysql://192.168.25.99:3306/dl_adb_all?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=GBK&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: '@jiushi123@'
          driver-class-name: com.mysql.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        ddb1:
          url: jdbc:mysql://192.168.25.99:3306/dl_ddb_1?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=GBK&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: '@jiushi123@'
          driver-class-name: com.mysql.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource 
        ldb1:
          url: jdbc:mysql://192.168.25.99:3306/dl_ldb_1?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=GBK&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: '@jiushi123@'
          driver-class-name: com.mysql.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        mdb1:
          url: jdbc:mysql://192.168.25.99:3306/dl_mdb_1?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=GBK&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: '@jiushi123@'
          driver-class-name: com.mysql.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 0
    host: 192.168.25.102
    port: 6379
    timeout: 5000ms
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms